server:
  port: 8088

spring:
  application:
    name: integration-service
  mail:
    host: mail.omshivlogistics.com
    port: 587
    username: ${MAIL_USERNAME:test@omshivlogistics.com}
    password: ${MAIL_PASSWORD:_kN-T;CK!.sOS3#@}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
